// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVbj4RPBE0Oo-kFq4Hi3aRbKu5dctlW4g',
    appId: '1:940974481749:web:f81ec772ec5f68b7124fdc',
    messagingSenderId: '940974481749',
    projectId: 'everyvaluation',
    authDomain: 'everyvaluation.firebaseapp.com',
    storageBucket: 'everyvaluation.appspot.com',
    measurementId: 'G-0SBZ1J1Q9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCjJNOByeBMEPzm3Absrl4c73el6vm6AE',
    appId: '1:940974481749:android:e7aaa234b472f0f1124fdc',
    messagingSenderId: '940974481749',
    projectId: 'everyvaluation',
    storageBucket: 'everyvaluation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl-YXVwDtSfBtuhVzwr7jMRKrsMXOzS9w',
    appId: '1:940974481749:ios:aa4e888aabbe40e0124fdc',
    messagingSenderId: '940974481749',
    projectId: 'everyvaluation',
    storageBucket: 'everyvaluation.appspot.com',
    iosClientId: '940974481749-rncvhtr0n4jsvcqo1hs32hecbhf0a8t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.everyvaluation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl-YXVwDtSfBtuhVzwr7jMRKrsMXOzS9w',
    appId: '1:940974481749:ios:aa4e888aabbe40e0124fdc',
    messagingSenderId: '940974481749',
    projectId: 'everyvaluation',
    storageBucket: 'everyvaluation.appspot.com',
    iosClientId: '940974481749-rncvhtr0n4jsvcqo1hs32hecbhf0a8t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.everyvaluation',
  );
}
